### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by 0mp** [nicolaprezza/CTLSAT#1]
Hello,

what's the license under which this software is published?

Thanks!

**Comment by 0mp** [comment]
I am asking because I am considering adding this nice piece of software to the FreeBSD Ports so that it is available as a binary package to FreeBSD users.

**Comment by nicolaprezza** [comment]
Hi, 

thanks for considering this code for FreeBSD! I usually use MIT, is that fine or do you prefer BSD (I would use the 2-clause one)?

**Comment by 0mp** [comment]
Oh my, the MIT license is perfect! I once read that the BSD-like licenses are preferred by  some academics (see [this post][1]) but I guess that it's not relevant in most cases.

Also, the license does not matter that much for the ports collection as long as it is open source software :)

Thanks a lot for your time! I'm looking forward to committing CTL-SAT with its new license!

[1]: https://github.com/github/choosealicense.com/issues/413#issuecomment-243598510

**Comment by nicolaprezza** [comment]
MIT license added. Thanks!

**Comment by 0mp** [comment]
Nice! Thank you!

FYI, https://www.freshports.org/math/ctl-sat/ ;)
